### ISSUE TITLE
bit, cmake, hdwallet issue

### ISSUE THREAD

**Issue by ghost3666** [Mizogg/TeamHunter#17]
C:\Users\Hassan\Downloads\TeamHunter-main (1)\TeamHunter-main\TeamHunter_Version1.5>pip install bit
Collecting bit
  Using cached bit-0.8.0-py3-none-any.whl.metadata (4.9 kB)
Collecting coincurve>=4.3.0 (from bit)
  Using cached coincurve-20.0.0.tar.gz (122 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      WARNING: Use build.verbose instead of cmake.verbose for scikit-build-core >= 0.10
      *** scikit-build-core 0.10.7 using CMake 3.31.2 (wheel)
      *** Configuring CMake...
      loading initial cache file C:\Users\Hassan\AppData\Local\Temp\tmp3kifbveg\build\CMakeInit.txt
      -- Building for: Visual Studio 17 2022
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (project):
        No CMAKE_C_COMPILER could be found.

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\Hassan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\Hassan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hassan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\Hassan\AppData\Local\Temp\pip-build-env-fcf4fick\overlay\Lib\site-packages\hatchling\build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hassan\AppData\Local\Temp\pip-build-env-fcf4fick\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 147, in build
          build_hook.initialize(version, build_data)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hassan\AppData\Local\Temp\pip-build-env-fcf4fick\overlay\Lib\site-packages\scikit_build_core\hatch\plugin.py", line 124, in initialize
          self._initialize(build_data=build_data)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hassan\AppData\Local\Temp\pip-build-env-fcf4fick\overlay\Lib\site-packages\scikit_build_core\hatch\plugin.py", line 226, in _initialize
          builder.configure(
          ~~~~~~~~~~~~~~~~~^
              defines=defines,
              ^^^^^^^^^^^^^^^^
          ...<2 lines>...
              version=Version(self.build_config.builder.metadata.version),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\Hassan\AppData\Local\Temp\pip-build-env-fcf4fick\overlay\Lib\site-packages\scikit_build_core\builder\builder.py", line 255, in configure
          self.config.configure(
          ~~~~~~~~~~~~~~~~~~~~~^
              defines=cmake_defines,
              ^^^^^^^^^^^^^^^^^^^^^^
              cmake_args=[*self.get_cmake_args(), *configure_args],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\Hassan\AppData\Local\Temp\pip-build-env-fcf4fick\overlay\Lib\site-packages\scikit_build_core\cmake.py", line 242, in configure
          raise FailedLiveProcessError(msg) from None
      scikit_build_core.errors.FailedLiveProcessError: CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ghost3666** [comment]
any suggestion or solution to my issue....
